In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/cardekho_dataset.csv',index_col=0)

In [ ]:
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [ ]:
#Model car name and Brand not needed features, only model enough

df.drop(['car_name','brand'],axis=1,inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  object
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.4+ MB

In [ ]:
df.isnull().sum()

model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['model'].value_counts()

model
i20             898
Swift Dzire     875
Swift           774
Alto            768
City            750
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [ ]:
df['fuel_type'].value_counts()

fuel_type
Petrol      7555
Diesel      7342
CNG          299
LPG           44
Electric       4
Name: count, dtype: int64

In [ ]:
df['transmission_type'].value_counts()

transmission_type
Manual       12094
Automatic     3150
Name: count, dtype: int64

In [ ]:
#Independent and Dependent features

X = df.drop('selling_price',axis=1)
y = df['selling_price']

In [ ]:
#train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
num_features = X.select_dtypes(exclude='object').columns
cat_features = X.select_dtypes(include='object').columns

In [ ]:
#OneHotEncoding and Standardization

from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(drop='first',handle_unknown='ignore'),cat_features),
                                     ('scaler',StandardScaler(),num_features)],remainder='passthrough')

In [ ]:
X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

Model Training and Selection

In [ ]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [ ]:
def evaluate_model(true,pred):
  mae = mean_absolute_error(true,pred)
  mse = mean_squared_error(true,pred)
  rmse = np.sqrt(mean_squared_error(true,pred))
  r2 = r2_score(true,pred)
  return mae,mse,r2,rmse

In [ ]:
#Dictionary of models

models = {
    'Linear Regression':LinearRegression(),
    'Ridge':Ridge(),
    'Lasso':Lasso(),
    'Decision Tree':DecisionTreeRegressor(),
    'Random Forest':RandomForestRegressor(),
    'KNN':KNeighborsRegressor(),
    'AdaBoost':AdaBoostRegressor()
}

In [ ]:
for name,model in models.items():
  model.fit(X_train,y_train)

  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  print(name)
  print("Training Performance")
  train_mae,train_mse,train_r2,train_rmse = evaluate_model(y_train,y_train_pred)
  print(f"  MAE: {train_mae}")
  print(f"  MSE: {train_mse}")
  print(f"   RMSE: {train_rmse}")
  print(f"  R2-Score: {train_r2}")

  print("Test Performance")
  test_mae,test_mse,test_r2,test_rmse = evaluate_model(y_test,y_test_pred)
  print(f"  MAE: {test_mae}")
  print(f"  MSE: {test_mse}")
  print(f"  RMSE: {test_rmse}")
  print(f"  R2-Score: {test_r2}")
  print("\n")

Linear Regression
Training Performance
  MAE: 171387.78132612942
  MSE: 126790305949.88167
   RMSE: 356076.2642326524
  R2-Score: 0.8505693753868585
Test Performance
  MAE: 169784.20012604728
  MSE: 123679036113.84785
  RMSE: 351680.30384689994
  R2-Score: 0.7965874993873232


Ridge
Training Performance
  MAE: 191039.991285686
  MSE: 165730941971.6824
   RMSE: 407100.65336680855
  R2-Score: 0.8046753023346899
Test Performance
  MAE: 184826.07040256233
  MSE: 130277498372.91463
  RMSE: 360939.7434100526
  R2-Score: 0.7857351370914235


Lasso
Training Performance
  MAE: 171405.12502988343
  MSE: 126791302734.8079
   RMSE: 356077.66390888364
  R2-Score: 0.8505682006109715
Test Performance
  MAE: 169782.7798322086
  MSE: 123689521465.63776
  RMSE: 351695.2110359732
  R2-Score: 0.7965702543335582


Decision Tree
Training Performance
  MAE: 4798.996856635234
  MSE: 387378021.04687715
   RMSE: 19681.92117266191
  R2-Score: 0.9995434497991564
Test Performance
  MAE: 125478.87832076091
  MSE: 109150933030.5018
  RMSE: 330379.9827933009
  R2-Score: 0.820481587425185


Random Forest
Training Performance
  MAE: 39413.25774210287
  MSE: 14808815644.328308
   RMSE: 121691.47728714738
  R2-Score: 0.9825468472929818
Test Performance
  MAE: 100794.37339271457
  MSE: 71533152604.57079
  RMSE: 267456.82381380885
  R2-Score: 0.8823508178491151


KNN
Training Performance
  MAE: 86077.25092250922
  MSE: 85860550720.94096
   RMSE: 293019.7104649122
  R2-Score: 0.8988077548378965
Test Performance
  MAE: 100338.92259757298
  MSE: 53994098744.05543
  RMSE: 232366.30294441452
  R2-Score: 0.9111969579569971


AdaBoost
Training Performance
  MAE: 350156.43157502083
  MSE: 192659294650.15317
   RMSE: 438929.7149318478
  R2-Score: 0.7729384867287914
Test Performance
  MAE: 351754.09018849523
  MSE: 228989008478.66406
  RMSE: 478527.9599758661
  R2-Score: 0.6233862399721014

Models Selected: 'KNN','RandomForest','AdaBoost'

HyperParameter Tuning

In [ ]:
rf_params = {
    'n_estimators':[100,200,500,1000],
    'max_depth':[None,5,15,8,10],
    'min_samples_split':[2,8,15,20],
    'max_features':['auto',5,7,8]
}
knn_params = {
    'n_neighbors':[2,3,10,20,40,50]
}
adb_params = {
    'n_estimators':[50,60,70,80],
    'loss':['linear','square','exponential']
}

In [ ]:
randomcv = [
    ('KNN',KNeighborsRegressor(),knn_params),
    ('Random Forest',RandomForestRegressor(),rf_params),
    ('AdaBoost',AdaBoostRegressor(),adb_params)
  ]

In [ ]:
#randomSearchCV

from sklearn.model_selection import RandomizedSearchCV

model_params = {}
for name,model,params in randomcv:
  random = RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=100,cv=3,verbose=2,n_jobs=-1)
  random.fit(X_train,y_train)

  model_params[name] = random.best_params_

for model_name in model_params:
  print(f"Best parameters for {model_name}: {model_params[model_name]}")

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 12 candidates, totalling 36 fits
Best parameters for KNN: {'n_neighbors': 3}
Best parameters for Random Forest: {'n_estimators': 500, 'min_samples_split': 2, 'max_features': 8, 'max_depth': None}
Best parameters for AdaBoost: {'n_estimators': 50, 'loss': 'linear'}

In [41]:
models = {
    'Random Forest':RandomForestRegressor(max_depth=None,min_samples_split=2,n_estimators=500,max_features=8),
    'KNN':KNeighborsRegressor(n_neighbors=3),
    'AdaBoost':AdaBoostRegressor(n_estimators=50,loss='linear')
}

for name,model in models.items():
  model.fit(X_train,y_train)

  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  print(name)
  print("Training Performance")
  train_mae,train_mse,train_r2,train_rmse = evaluate_model(y_train,y_train_pred)
  print(f"  MAE: {train_mae}")
  print(f"  MSE: {train_mse}")
  print(f"  RMSE: {train_rmse}")
  print(f"  R2-Score: {train_r2}")

  print("Test Performance")
  test_mae,test_mse,test_r2,test_rmse = evaluate_model(y_test,y_test_pred)
  print(f"  MAE: {test_mae}")
  print(f"  MSE: {test_mse}")
  print(f"  RMSE: {test_rmse}")
  print(f"  R2-Score: {test_r2}")
  print("\n")

Random Forest
Training Performance
  MAE: 39638.683439577595
  MSE: 20712965812.80679
  RMSE: 143919.99796000135
  R2-Score: 0.9755884221919787
Test Performance
  MAE: 97648.11764789272
  MSE: 43910897638.508514
  RMSE: 209549.27257928747
  R2-Score: 0.9277806023279945


KNN
Training Performance
  MAE: 74964.84898182315
  MSE: 63455370737.95043
  RMSE: 251903.49489030603
  R2-Score: 0.9252137171419197
Test Performance
  MAE: 101374.87700885536
  MSE: 70317646805.87442
  RMSE: 265174.7476775917
  R2-Score: 0.884349936550157


AdaBoost
Training Performance
  MAE: 411057.8978856905
  MSE: 241815716802.03027
  RMSE: 491747.6149428996
  R2-Score: 0.7150044450773277
Test Performance
  MAE: 411616.3934373209
  MSE: 277269463858.26166
  RMSE: 526563.8269557278
  R2-Score: 0.5439803158311458

Thus Random forest has best improvement in accuracy after HyperParameter Tuning