In [1]:
import pandas as pd
from io import StringIO
data = '{"empployee_name":"Ishika Saha", "email":"ishika.saha@gmail.com", "job-profile":[{"Title1":"Team Lead","Title2":"Sr. Data Scientist"}]}'
df = pd.read_json(StringIO(data))

In [2]:
df

,empployee_name,email,job-profile
0,Ishika Saha,ishika.saha@gmail.com,"{'Title1': 'Team Lead', 'Title2': 'Sr. Data Sc..."

In [3]:
# Dataframe is converted to json format where key is the col names

df.to_json()

'{"empployee_name":{"0":"Ishika Saha"},"email":{"0":"ishika.saha@gmail.com"},"job-profile":{"0":{"Title1":"Team Lead","Title2":"Sr. Data Scientist"}}}'

In [4]:

df.to_json(orient = 'index')

'{"0":{"empployee_name":"Ishika Saha","email":"ishika.saha@gmail.com","job-profile":{"Title1":"Team Lead","Title2":"Sr. Data Scientist"}}}'

In [5]:

df.to_json(orient = 'records')

'[{"empployee_name":"Ishika Saha","email":"ishika.saha@gmail.com","job-profile":{"Title1":"Team Lead","Title2":"Sr. Data Scientist"}}]'

In [6]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header = None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [9]:
df.to_csv("wine.csv")       # converting df to csv again

In [12]:
%pip install lxml

Collecting lxml
  Downloading lxml-5.3.0-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Downloading lxml-5.3.0-cp312-cp312-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/3.8 MB 2.3 MB/s eta 0:00:02
   ---------------- ----------------------- 1.6/3.8 MB 2.5 MB/s eta 0:00:01
   --------------------- ------------------ 2.1/3.8 MB 2.7 MB/s eta 0:00:01
   ------------------------ --------------- 2.4/3.8 MB 2.5 MB/s eta 0:00:01
   --------------------------- ------------ 2.6/3.8 MB 2.0 MB/s eta 0:00:01
   ------------------------------ --------- 2.9/3.8 MB 1.9 MB/s eta 0:00:01
   -------------------------------- ------- 3.1/3.8 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 1.8 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-5.3.0
Note: you may need to restart the kernel to use updated packages.

In [13]:
df2 = pd.read_html("https://www.fdic.gov/bank-failures/failed-bank-list")

In [15]:
df2

[                               Bank Name               City         State  \
 0                   Pulaski Savings Bank            Chicago      Illinois
 1     The First National Bank of Lindsay            Lindsay      Oklahoma
 2  Republic First Bank dba Republic Bank       Philadelphia  Pennsylvania
 3                          Citizens Bank           Sac City          Iowa
 4               Heartland Tri-State Bank            Elkhart        Kansas
 5                    First Republic Bank      San Francisco    California
 6                         Signature Bank           New York      New York
 7                    Silicon Valley Bank        Santa Clara    California
 8                      Almena State Bank             Almena        Kansas
 9             First City Bank of Florida  Fort Walton Beach       Florida

     Cert                 Aquiring Institution      Closing Date  \
 0  28611                      Millennium Bank  January 17, 2025
 1   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024
 2  27332    Fulton Bank, National Association    April 26, 2024
 3   8758            Iowa Trust & Savings Bank  November 3, 2023
 4  25851               Dream First Bank, N.A.     July 28, 2023
 5  59017            JPMorgan Chase Bank, N.A.       May 1, 2023
 6  57053                  Flagstar Bank, N.A.    March 12, 2023
 7  24735  First Citizens Bank & Trust Company    March 10, 2023
 8  15426                          Equity Bank  October 23, 2020
 9  16748            United Fidelity Bank, fsb  October 16, 2020

    Fund  Sort ascending
 0                 10548
 1                 10547
 2                 10546
 3                 10545
 4                 10544
 5                 10543
 6                 10540
 7                 10539
 8                 10538
 9                 10537  ]

In [16]:
df2[0]

,Bank Name,City,State,Cert,Aquiring Institution,Closing Date,Fund Sort ascending
0,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
1,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,"First Bank & Trust Co., Duncan, OK","October 18, 2024",10547
2,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
3,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
4,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
5,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
6,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
7,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
8,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
9,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537

In [21]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"
df3 = pd.read_html(url,match = "Operator",header=0)

In [22]:
df3[1]

,MCC,MNC,Brand,Operator,Status,Bands (MHz),References and notes
0,901,1,NaN,Webbing,Unknown,MVNO,Former ICO Satellite Management[51][52]
1,901,2,NaN,GlobalmatiX AG,Unknown,Unknown,Former Sense Communications International; veh...
2,901,3,Iridium,NaN,Operational,Satellite,NaN
3,901,4,NaN,BBIX Singapore Pte. Ltd.,Unknown,Unknown,Former Globalstar[54]
4,901,5,NaN,Thuraya RMSS Network,Operational,Satellite,NaN
...,...,...,...,...,...,...,...
99,902,1,NaN,MulteFire Alliance,Operational,LTE,[6][123]
100,991,1,NaN,World's Global Telecom,Not operational,Unknown,temporarily assigned until 15 January 2021[102...
101,991,2,5G Croco,Orange S.A.,Not operational,5G,temporarily assigned until 6 August 2022[125][...
102,991,3,NaN,Halys SAS,Not operational,Unknown,temporary assignment for trial until 5 April 2...
103,991,4,NaN,E-Space Inc.,Unknown,Satellite,temporary assignment for trial until 17 Oct 20...

In [26]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [30]:
df_excel = pd.read_excel('sample_data.xlsx')
df_excel

     Name  Age
0  Soniya   20
1   Rahul   21
2     Raj   25

In [ ]:
# Pickle file  is completely serialized that is stored in binary format
df_excel.to_pickle('df_excel')

In [35]:
pd.read_pickle('df_excel')

     Name  Age
0  Soniya   20
1   Rahul   21
2     Raj   25